version: "2"
services:
  api:
    cpu_shares: 100
    entrypoint: bash ./docker-entrypoint.sh
    environment:
      - DJANGO_ENV=$DJANGO_ENV
      - DJANGO_DB_NAME=$DJANGO_DB_NAME
      - DJANGO_DB_USER=$DJANGO_DB_USER
      - DJANGO_DB_PASSWORD=$DJANGO_DB_PASSWORD
      - DJANGO_DB_HOST=$DJANGO_DB_HOST
      - DJANGO_DB_PORT=$DJANGO_DB_PORT
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - PLAID_CLIENT_ID=$PLAID_CLIENT_ID
      - PLAID_PUBLIC_KEY=$PLAID_PUBLIC_KEY
      - PLAID_SECRET=$PLAID_SECRET
      - PLAID_ENV=$PLAID_ENV
    image: 102953801091.dkr.ecr.us-east-1.amazonaws.com/api
    logging:
      driver: awslogs
      options:
        awslogs-group: wilbur
        awslogs-region: us-east-1
        awslogs-stream-prefix: api
    mem_limit: 262144000
    ports:
      - 8000:8000
  web:
    cpu_shares: 100
    entrypoint: bash ./docker-entrypoint.sh
    environment:
      - REACT_APP_PLAID_ENV=$PLAID_ENV
      - REACT_APP_PLAID_PUBLIC_KEY=$PLAID_PUBLIC_KEY
    image: 102953801091.dkr.ecr.us-east-1.amazonaws.com/web
    logging:
      driver: awslogs
      options:
        awslogs-group: wilbur
        awslogs-region: us-east-1
        awslogs-stream-prefix: web
    mem_limit: 262144000
    ports:
      - 5000:5000
  nginx:
    cpu_shares: 100
    entrypoint: bash ./etc/nginx/docker-entrypoint.sh
    environment:
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY=$SSL_CERTIFICATE_KEY
    image: 102953801091.dkr.ecr.us-east-1.amazonaws.com/nginx
    logging:
      driver: awslogs
      options:
        awslogs-group: wilbur
        awslogs-region: us-east-1
        awslogs-stream-prefix: nginx
    mem_limit: 262144000
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - api
      - web
