version: "2"
services:
  api:
    build: ./api
    command: uwsgi --ini uwsgi.ini --py-autoreload 1
    container_name: api
    environment:
      - DJANGO_ENV=$DJANGO_ENV
      - DJANGO_DB_NAME=$DJANGO_DB_NAME
      - DJANGO_DB_USER=$DJANGO_DB_USER
      - DJANGO_DB_PASSWORD=$DJANGO_DB_PASSWORD
      - DJANGO_DB_HOST=$DJANGO_DB_HOST
      - DJANGO_DB_PORT=$DJANGO_DB_PORT
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - PLAID_CLIENT_ID=$PLAID_CLIENT_ID
      - PLAID_PUBLIC_KEY=$PLAID_PUBLIC_KEY
      - PLAID_SECRET=$PLAID_SECRET
      - PLAID_ENV=$PLAID_ENV
    expose:
      - 8000
    restart: always
    volumes:
      - ./api:/home/api
  web:
    build: ./web
    command: yarn start
    container_name: web
    environment:
      - REACT_APP_NGROK_ID=bd2f52a9
      - REACT_APP_PLAID_ENV=$PLAID_ENV
      - REACT_APP_PLAID_PUBLIC_KEY=$PLAID_PUBLIC_KEY
    expose:
      - 3000
    restart: always
    volumes:
      - ./web:/home/web
  nginx:
    build: ./nginx
    command: bash -c "envsubst < /etc/nginx/nginx.conf.dev > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    container_name: nginx
    environment:
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY=$SSL_CERTIFICATE_KEY
    depends_on:
      - api
      - web
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf.dev
    volumes_from:
      - api
      - web
