# Generated by Django 2.0.3 on 2019-01-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iv',
            field=models.CharField(max_length=24, verbose_name='iv'),
        ),
    ]
